In [1]:
import numpy as np
x=np.array([[0,0,1],
           [0,1,1],
           [1,0,1],
           [1,1,1],
           [1,0,1],
           [1,1,1]])
y=np.array([[0],
           [1],
           [1],
           [0],
           [1],
           [0]])

In [2]:
np.shape(x)
np.shape(y)

(6, 1)

In [3]:
# weights of Hidden layers
np.random.seed(101)
w1=2*np.random.random((3,5))-1
w2=2*np.random.random((5,7))-1
w3=2*np.random.random((7,5))-1
w4=2*np.random.random((5,1))-1
print(w4)

[[-0.59294476]
 [-0.40195918]
 [-0.54468821]
 [-0.90366223]
 [ 0.80794271]]


In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [5]:
def derivative(x):
    return x*(1-x)

In [6]:
def mse(y,ycap):
    return ((y-ycap)**2).mean()

In [7]:
def train(x,y,w,iter,conv=0.00000001):
    W1=w[0]
    W2=w[1]
    W3=w[2]
    W4=w[3]
    perr=0
    for i in range(iter):
        #Find out the Activation function in forward direction
        l1=sigmoid(x.dot(W1))
        l2=sigmoid(l1.dot(W2))
        l3=sigmoid(l2.dot(W3))
        l4=sigmoid(l3.dot(W4))
        cerr = mse(y,l4)
        if i%250==0:
            print("current error for every 250 iter",cerr)
            
        diff=abs(perr-cerr)
        j=0
        if diff<=conv:
            print("training completed agfter ",i+1,"iter")
            j=1
            break
            # find out error and darivatives for each layer in backward direction
        e4=y-l4
        delta4=e4*derivative(l4)
        
        e3=delta4.dot(W4.T)
        delta3=e3*derivative(l3)
        
        e2=delta3.dot(W3.T)
        delta2=e2*derivative(l2)
        
        e1=delta2.dot(W2.T)
        delta1=e1*derivative(l1)
        # Adjusting the weights for all layers
        W1+=x.T.dot(delta1)
        W2+=l1.T.dot(delta2)
        W3+=l2.T.dot(delta3)
        W4+=l3.T.dot(delta4)
        perr=cerr
    if j==0:
        print("training not yet completed")

    return[W1,W2,W3,W4]

In [8]:
theta=train(x,y,[w1,w2,w3,w4],10000)

current error for every 250 iter 0.26860899928826326
current error for every 250 iter 0.15941616879252865
current error for every 250 iter 0.12713600005857492
current error for every 250 iter 0.012223155463306287
current error for every 250 iter 0.0019838241524214643
current error for every 250 iter 0.0009083194419106257
current error for every 250 iter 0.0005501558663063793
current error for every 250 iter 0.00038144807387436984
current error for every 250 iter 0.0002863818028939878
current error for every 250 iter 0.0002265242785762525
current error for every 250 iter 0.000185873980619259
current error for every 250 iter 0.0001567114057023876
current error for every 250 iter 0.00013490276297571083
current error for every 250 iter 0.00011805448026099373
current error for every 250 iter 0.00010469372854521265
current error for every 250 iter 9.386901053379987e-05
current error for every 250 iter 8.494060926123975e-05
current error for every 250 iter 7.74638711728748e-05
current error f

In [9]:
print(w1)

[[-1.79160702  3.36228665 -4.15277106 -1.1135678   2.04606174]
 [ 2.31550669 -2.71548858  4.07476616  0.06365725 -2.49872364]
 [ 0.72956785  0.9338406   1.01510335  0.98196087  1.0888418 ]]


In [10]:
theta[0] # here w and theta valuesw are same so split them using another methiode

array([[-1.79160702,  3.36228665, -4.15277106, -1.1135678 ,  2.04606174],
       [ 2.31550669, -2.71548858,  4.07476616,  0.06365725, -2.49872364],
       [ 0.72956785,  0.9338406 ,  1.01510335,  0.98196087,  1.0888418 ]])

In [11]:
# to get different values of theta and w
w=[np.array(w1),np.array(w2),np.array(w3),np.array(w4)]
th=train(x,y,w,10000)

current error for every 250 iter 4.505635723739577e-05
training completed agfter  2 iter


In [12]:
print(w1)

[[-1.79160702  3.36228665 -4.15277106 -1.1135678   2.04606174]
 [ 2.31550669 -2.71548858  4.07476616  0.06365725 -2.49872364]
 [ 0.72956785  0.9338406   1.01510335  0.98196087  1.0888418 ]]


In [13]:
th[0]

array([[-1.79161862,  3.36229714, -4.15277156, -1.1135646 ,  2.04607344],
       [ 2.31551214, -2.71550302,  4.0747743 ,  0.06365941, -2.49873416],
       [ 0.72956481,  0.9338491 ,  1.01511079,  0.98196403,  1.08884599]])

In [14]:
def predict(x,w):
    r=x
    for v in w:
        r=sigmoid(r.dot(v))
    return r

In [15]:
ycap=predict(x,th)
print(ycap)

[[0.00676356]
 [0.98797577]
 [0.99583289]
 [0.00475503]
 [0.99583289]
 [0.00475503]]


In [16]:
#ycap1=predict(x,theta)
#print(ycap1)

In [17]:
ycap=predict(x,theta)
print(ycap)

[[0.00676432]
 [0.98797447]
 [0.99583239]
 [0.00475557]
 [0.99583239]
 [0.00475557]]


In [18]:
print(np.c_[y.ravel(),ycap.ravel()])

[[0.         0.00676432]
 [1.         0.98797447]
 [1.         0.99583239]
 [0.         0.00475557]
 [1.         0.99583239]
 [0.         0.00475557]]


In [19]:
print(w1)

[[-1.79160702  3.36228665 -4.15277106 -1.1135678   2.04606174]
 [ 2.31550669 -2.71548858  4.07476616  0.06365725 -2.49872364]
 [ 0.72956785  0.9338406   1.01510335  0.98196087  1.0888418 ]]


In [20]:
ycap[ycap>=0.5]=1
ycap[ycap<=0.5]=0
print(ycap)

[[0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]]


In [23]:
def acc_clf(y,ycap):
    r=y==ycap
    pcnt=r[r==True].size
    n=y.size
    acc=pcnt/n*100
    return acc

In [24]:
acc_clf(y,ycap)

100.0